"use client"

import * as React from "react"
import {
    AppHeader,
    Avatar,
    Badge,
    Button,
    ButtonGroup,
    Card,
    Checkbox,
    Chicklet,
    Collapsible,
    DatePicker,
    Divider,
    Dropdown,
    FileCard,
    FileThumbnail,
    FileTypeIcon,
    FileValidationCard,
    Footer,
    Icon,
    Illustration,
    Input,
    Label,
    Logo,
    NavigationLauncher,
    NavigationPopover,
    ProgressBar,
    ProgressList,
    QuickFilters,
    RadioGroup,
    RadioSelector,
    ReadOnly,
    SegmentedTabs,
    SimpleColumnLayout,
    Spacer,
    StackedBarChart,
    Statistic,
    Steps,
    StepsItem,
    SubText,
    Switch,
    Table,
    Tabs,
    Text,
    Tooltip,
    Typography,
    Upload,
    UploadButton,
    UploadItem,
    UploadThumbnail,
    UploadZone,
    UserProfile,
    UserProfileDropdown,
    Textarea,
    Skeleton,
    Alert,
    Breadcrumb,
    Pagination,
    NotificationProvider,
    Modal,
    Drawer,
    AreaChart,
    LineChart,
    BarChart,
    PieChart,
    DoughnutChart,
    RadarChart,
    PolarAreaChart,
    ScatterChart,
    BubbleChart,
    RadialChart,
} from "../../src"

import { Plus as PlusIcon, ArrowRight as ArrowRightIcon, Pencil as PencilIcon } from "lucide-react"

// Sample data for component examples
const sampleOptions = [
  { value: 'option1', label: 'Option 1' },
  { value: 'option2', label: 'Option 2' },
  { value: 'option3', label: 'Option 3' },
];

const sampleOptionsWithDisabled = [
  { value: 'small', label: 'Small' },
  { value: 'medium', label: 'Medium' },
  { value: 'large', label: 'Large' },
  { value: 'xlarge', label: 'Extra Large', disabled: true },
];

const sampleButtons = [
  { id: 'ghost', label: 'Button', variant: 'text', icon: 'add', iconPosition: 'leading' },
  { id: 'outline', label: 'Button', variant: 'secondary', icon: 'add', iconPosition: 'leading' },
  { id: 'filled', label: 'Button', variant: 'primary', icon: 'add', iconPosition: 'leading' },
];

export const registry: Record<string, React.ComponentType<any> | any> = {
    React,
    AppHeader,
    Avatar,
    Badge,
    Button,
    ButtonGroup,
    Card,
    Checkbox,
    Chicklet,
    Collapsible,
    DatePicker,
    Divider,
    Dropdown,
    FileCard,
    FileThumbnail,
    FileTypeIcon,
    FileValidationCard,
    Footer,
    Icon,
    Illustration,
    Input,
    Label,
    Logo,
    Logos: Logo, // Alias for Logo component
    NavigationLauncher,
    NavigationPopover,
    ProgressBar,
    ProgressList,
    QuickFilters,
    RadioGroup,
    RadioSelector,
    ReadOnly,
    SegmentedTabs,
    SimpleColumnLayout,
    Spacer,
    StackedBarChart,
    Statistic,
    Steps,
    StepsItem,
    SubText,
    Switch,
    Table,
    Tabs,
    Text,
    Tooltip,
    Typography,
    Upload,
    UploadButton,
    UploadItem,
    UploadThumbnail,
    UploadZone,
    UserProfile,
    UserProfileDropdown,
    Textarea,
    Skeleton,
    Alert,
    Breadcrumb,
    Pagination,
    NotificationProvider,
    Modal,
    Drawer,
    AreaChart,
    LineChart,
    BarChart,
    PieChart,
    DoughnutChart,
    RadarChart,
    PolarAreaChart,
    ScatterChart,
    BubbleChart,
    RadialChart,
    PlusIcon,
    ArrowRightIcon,
    PencilIcon,
    sampleOptions,
    sampleOptionsWithDisabled,
    sampleButtons,
}

