import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "../../../src/styles/globals.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

import { ThemeProvider } from "@/components/theme-provider"
import { GlassProvider } from "@/components/glass-provider"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background font-sans text-foreground`}
      >
        <Script
          id="theme-detection"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme') || 'light';

                  // Remove all theme classes first
                  document.documentElement.classList.remove('light', 'dark', 'night');

                  if (theme === 'dark' || theme === 'night' || theme === 'light') {
                    document.documentElement.classList.add(theme);
                  } else {
                    document.documentElement.classList.add('light');
                  }

                  // Glass mode FOUC prevention
                  var glass = localStorage.getItem('ft-glass-mode');
                  document.documentElement.classList.remove('theme-glass', 'theme-glass-subtle', 'theme-glass-prominent');
                  if (glass === 'true') document.documentElement.classList.add('theme-glass');
                  else if (glass === 'subtle') document.documentElement.classList.add('theme-glass-subtle');
                  else if (glass === 'prominent') document.documentElement.classList.add('theme-glass-prominent');
                } catch (e) {}
              })();
            `,
          }}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
          themes={['light', 'dark', 'night']}
        >
          <GlassProvider defaultGlass={false} storageKey="ft-glass-mode">
            {children}
          </GlassProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
